version: "3.4"

# Development environment override
services:
    php:
        container_name: programmierprojekt_php
        build:
            target: app_php_dev
        volumes:
            - ./:/srv/app
            - ./docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
            # If you develop on Mac or Windows you can remove the vendor/ directory
            #  from the bind-mount for better performance by enabling the next line:
            #- /srv/app/vendor
        environment:
            # See https://xdebug.org/docs/all_settings#mode
            XDEBUG_MODE: "${XDEBUG_MODE:-off}"
        extra_hosts:
            # Ensure that host.docker.internal is correctly defined on Linux
            - host.docker.internal:host-gateway

    caddy:
        container_name: programmierprojekt_caddy
        volumes:
            - ./public:/srv/app/public:ro
            - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro

    ###> symfony/mercure-bundle ###
    ###< symfony/mercure-bundle ###

    ###> doctrine/doctrine-bundle ###

    ###< doctrine/doctrine-bundle ###

    ###> symfony/mailer ###
    mailer:
        container_name: programmierprojekt_mail
        image: schickling/mailcatcher
        ports: ["1025", "1080"]
###< symfony/mailer ###
